name: alarm_cycle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  intl: ^0.19.0
  path_provider: ^2.1.0
  provider: ^6.1.1
  path: ^1.8.3
  permission_handler: ^11.1.0
  background_fetch: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
